version: '3.8'

services:
  backend:
    build: ./social_backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://ahmedbasharsyed455:mlFrbxsTlnldYVtZ@cluster0.zlqtt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - PORT=5000
    volumes:
      - ./social_backend/uploads:/app/uploads  # Persist uploaded files
    networks:
      - app-network

  frontend:
    build: ./social_frontend
    ports:
      - "3000:80"  # Access the React app at http://localhost:3000
    networks:
      - app-network

  reverse-proxy:
    image: nginx:latest
    container_name: reverse-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
      - frontend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
