name: Deploy Backend to AWS EC2

on:
  push:
    branches: [ "main" ]
    

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to DockerHub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker Image
        run: |
          cd social_backend
          docker build -t ${{ secrets.DOCKER_USERNAME }}/social_backend:latest .

      - name: Push Docker Image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/social_backend:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            
            docker stop backend-container || true
            docker rm backend-container || true
            docker run --init -d -p 5000:5000 --name backend-container  -e MONGO_URI="mongodb+srv://ahmedbasharsyed455:mlFrbxsTlnldYVtZ@cluster0.zlqtt.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" ${{ secrets.DOCKER_USERNAME }}/social_backend:latest
